name: Create Env File

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  
jobs:
  create_env:
    runs-on: ubuntu-20.04
    environment:
      name: production
    
    steps:
      - name: install jq
        run: sudo apt-get install jq

      - name: Parse JSON and create env file
        shell: bash
        env:
          SECRETS_CONTEXT: ${{ toJson(vars) }}
        run: |
          echo "$SECRETS_CONTEXT" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > env_file.txt

      - name: list all files and folders
        run: ls -la

      - name: read file
        run: cat env_file.txt
