name: Create Env File

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed
  
jobs:
  create_env:
    runs-on: ubuntu-20.04
    steps:
      - name: view the secrets context
        shell: bash
        run: echo "$SECRETS_CONTEXT"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}
